### ISSUE TITLE
Setting language without LanguageSwitcherDialog

### ISSUE THREAD

**Issue by aitbaali** [ahmedaljazzar/LanguageSwitcher#16]
Hello, Amazing work.
I want to set language programmatically without showing the Dialog of languages.
Something like `ls.setlanguage("En") `or similar.

**Comment by iamjazzar** [comment]
Hello @aitbaali:

You can use one of the following methods to set your app locale manually from an activity:

```JAVA
// USAGE: ls.setLocale("En", this)
public boolean setLocale(String newLocale, Activity activity);
// USAGE: ls.setLocale(Locale.ENGLISH , this)
public boolean setLocale(Locale newLocale, Activity activity);
```

**Comment by iamjazzar** [comment]
If this does not solve your issue, please tell.

**Comment by aitbaali** [comment]
@ahmedaljazzar sorry for my late response, I was busy, I will give it a try.
